<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Salir</name>
   <tag></tag>
   <elementGuidId>dd9acfe3-b3fd-423d-b653-d54261ff8800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Salir']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>b6f77a8e-cd8b-4774-90ae-e996e6a87753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>1a6a9433-f639-42bd-b2b7-834203bfede5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;encabezado&quot;]/table[1]/tbody[1]/tr[1]/td[3]/a[@class=&quot;boton&quot;]/font[1]/b[1]</value>
      <webElementGuid>3e4dbd4f-b1ba-4bf0-99d7-2dfe6e04e45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Modulo_Hojas_De_Vida/1.Consulta_Datos_Laborales/Page_Sistema de Recursos Humanos y Nmina/frame_html1frameset1frame1_encabezado</value>
      <webElementGuid>787aaf55-2041-47bf-a45b-615fc4b2bb6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salir']/parent::*</value>
      <webElementGuid>64b9cb31-3492-40ee-ab31-59647922e989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>3a25b168-59e6-487e-9a26-b8c7d534f6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Salir' or . = 'Salir')]</value>
      <webElementGuid>9ff5d58b-2c33-49eb-894b-de28f77eca17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
