<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_html1frameset1frameset1frameset1frame2_menu</name>
   <tag></tag>
   <elementGuidId>f6ebf880-3186-45bf-b7e7-75b38be0aabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>321c90dc-2149-4918-b9ee-bac36262c672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Q7AON/getMenuModulo.do</value>
      <webElementGuid>bac9783e-7c87-49fb-89b4-a1a47fbb4451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>99bbfa9c-1554-499a-b251-d87401dfa7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>08bf62ad-9c36-4357-9283-311beb7e49ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>900d7570-d343-47ce-a16d-068ab537c9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frameset[1]/frame[2]</value>
      <webElementGuid>5d1ecf09-0bc9-4bd9-8d6b-606c550d0e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='menu']</value>
      <webElementGuid>f81d0c75-b665-4694-ac2d-7e0de9676f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame[2]</value>
      <webElementGuid>e63f5652-3fc2-47c9-9d76-bc87181498e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '/Q7AON/getMenuModulo.do' and @name = 'menu']</value>
      <webElementGuid>b4084c2f-83e8-42a1-b39a-c6e83661bc7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
