<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sistemas De Apoyo_moduloMiniatura</name>
   <tag></tag>
   <elementGuidId>7ddac842-2139-4551-b690-449f5c5b0a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a > img.moduloMiniatura</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Hojas De Vida De Empleados Y Dependientes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5c854b0-fa43-457d-b72c-57a942241b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moduloMiniatura</value>
      <webElementGuid>96087345-a591-407a-8b31-c6c5201d627c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Q7AON/imagenes/rhmodhdv.png</value>
      <webElementGuid>c0bc3fe0-10e4-44c1-826f-ec9607cf5a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hojas De Vida De Empleados Y Dependientes</value>
      <webElementGuid>f352957f-1df9-4c20-8b1f-ca18732ee4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[2]/tbody[1]/tr[2]/td[2]/a[1]/img[@class=&quot;moduloMiniatura&quot;]</value>
      <webElementGuid>a689fad0-9be5-4a52-9d8a-e973b9152cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Modulo_Hojas_De_Vida/1.Consulta_Datos_Laborales/Page_Sistema de Recursos Humanos y Nmina/frame_formas</value>
      <webElementGuid>5889978e-008b-4d07-b115-3033affc2239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hojas De Vida De Empleados Y Dependientes']</value>
      <webElementGuid>daccb170-df25-4471-89de-50d52d8cfddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/img</value>
      <webElementGuid>7156463a-1b21-4da2-93c9-79a0e279fadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Q7AON/imagenes/rhmodhdv.png' and @alt = 'Hojas De Vida De Empleados Y Dependientes']</value>
      <webElementGuid>364c9b65-5363-4927-bb73-3ea96cc2ce12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
