<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clave_clave</name>
   <tag></tag>
   <elementGuidId>3470aca0-9fd0-468a-b46c-f0f0ad03696d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;clave&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='clave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>876aec75-f245-4082-bb9a-af3a46c89541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7e2c1912-c1ef-40b2-8654-9dd9cdd4258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>clave</value>
      <webElementGuid>348067f8-1496-4016-baf9-ccf36667cf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>campo</value>
      <webElementGuid>db55973e-4c3a-4f4d-b466-090d2c081375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>56cde89b-6d9c-4e8d-8a2d-aa1465c997f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/form[1]/table[@class=&quot;externa&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;interna&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;campo&quot;]</value>
      <webElementGuid>2e13a20e-ca20-4075-906d-a181691edf58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='clave']</value>
      <webElementGuid>162d44b4-12de-4ed3-b0ec-c968372f9c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>fc79cc37-6a9d-4c68-b798-40e2580b8253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'clave']</value>
      <webElementGuid>e99b9bd0-df85-4f5c-b46e-a12b673fc09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
